name: Custom score build
description: "Create a custom ossia score build"
inputs:
  cmake-options:
    description: 'Additional CMake options'
    required: true
  cmake-cache:
    description: 'Custom CMake cache file'
    required: false
  score-repo:
    description: 'Custom ossia score repo'
    required: true
    default: 'ossia/score'
  score-ref:
    description: 'Custom ref to use'
    required: true
    default: 'master'
  macos-certificate-base64:
    description: 'Base64-encoded P12 certificate for macOS code signing (optional)'
    required: false
    default: ''
  macos-certificate-password:
    description: 'Password for macOS P12 certificate (optional)'
    required: false
    default: ''
  macos-notarize-team-id:
    description: 'Apple Developer Team ID for notarization (optional)'
    required: false
    default: ''
  macos-notarize-apple-id:
    description: 'Apple ID for notarization (optional)'
    required: false
    default: ''
  macos-notarize-password:
    description: 'App-specific password for notarization (optional)'
    required: false
    default: ''

outputs:
  artifact-id:
    description: "Output artifact id containing built score release"
    value: ${{ steps.upload.outputs.artifact-id }}

runs:
  using: 'composite'
  steps:
    - name: Long path support
      if: runner.os == 'Windows'
      shell: bash
      run: git config --global core.longpaths true

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.score-repo }}
        path: score-src
        ref: ${{ inputs.score-ref }}
        submodules: 'recursive'

    - uses: maxim-lobanov/setup-xcode@v1
      if: runner.os == 'macOS'
      with:
        xcode-version: '>=16'

    - uses: jcelerier/import-codesign-certs@master
      if: runner.os == 'macOS' && inputs.macos-certificate-base64 != ''
      with:
        p12-file-base64: ${{ inputs.macos-certificate-base64 }}
        p12-password: ${{ inputs.macos-certificate-password }}

    - name: Dependencies
      shell: bash
      working-directory: score-src
      run: |
        if [[ "$RUNNER_ARCH" == "ARM64" ]]; then
          export CPU_ARCH=aarch64
        else
          export CPU_ARCH=x86_64
        fi
        export MACOS_ARCH=$CPU_ARCH
        
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          ./ci/appimage.deps.sh
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          ./ci/win32.deps.sh
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          ./ci/osx.package.deps.sh
        fi

      env:
        MAC_CERT_B64: ${{ inputs.macos-certificate-base64 }}
        MAC_CODESIGN_PASSWORD:  ${{ inputs.macos-certificate-password }}

    - name: Build
      shell: bash
      working-directory: score-src
      run: |
        if [[ "$RUNNER_ARCH" == "ARM64" ]]; then
          export CPU_ARCH=aarch64
        else
          export CPU_ARCH=x86_64
        fi
        export MACOS_ARCH=$CPU_ARCH
        
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          ./ci/appimage.build.sh
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          ./ci/win32.build.sh
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          ./ci/osx.package.build.sh
        fi
      env:
        SCORE_EXTRA_CMAKE_ARGS: ${{ inputs.cmake-options }}
        SCORE_CMAKE_CACHE: ${{ inputs.cmake-cache }}

    - name: Deploy
      id: deploy
      shell: bash
      working-directory: score-src
      run: |
        if [[ "$RUNNER_ARCH" == "ARM64" ]]; then
          export CPU_ARCH=aarch64
        else
          export CPU_ARCH=x86_64
        fi
        export MACOS_ARCH=$CPU_ARCH
        export CI_IS_AZURE=0
        
        export GITTAGNOV=$(echo "$GITHUB_REF" | sed "s/.*\///;s/^v//")
        export BUILD_ARTIFACTSTAGINGDIRECTORY="$PWD/staging"
        mkdir -p "$BUILD_ARTIFACTSTAGINGDIRECTORY"
        
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          ./ci/appimage.deploy.sh
          echo "release-name=appimage-$CPU_ARCH" >> $GITHUB_OUTPUT
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          ./ci/win32.deploy.sh
          echo "release-name=windows-$CPU_ARCH" >> $GITHUB_OUTPUT
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          ./ci/osx.package.deploy.sh
          echo "release-name=macos-$CPU_ARCH" >> $GITHUB_OUTPUT
        fi
      env:
        MAC_ALTOOL_PASSWORD: ${{ inputs.macos-notarize-password }}

    - name: Upload build
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.deploy.outputs.release-name }}
        path: |
          score-src/staging/*.*
