name: 'Package Custom ossia score App'
description: 'Creates custom branded ossia score applications with QML UI and score files'
inputs:
  app-name:
    description: 'Name of the custom application'
    required: true
  app-organization:
    description: 'Organization name (e.g. ossia)'
    required: true
    default: ''
  app-domain:
    description: 'Organization domain (e.g. ossia.io)'
    required: true
    default: ''
  app-identifier:
    description: 'App identifier in reverse-DNS (e.g. io.ossia.score)'
    required: true
    default: ''
  app-description:
    description: 'One-line description of your app'
    required: true
    default: ''
  app-environment:
    description: 'Optional environment variables'
    required: false
    default: ''
  app-copyright:
    description: 'One-line copyright of your app'
    required: true
    default: ''
  app-version:
    description: 'Version number, e.g. 4.0.1'
    required: true
    default: ''
  app-appdata-xml:
    description: 'Path to .appdata.xml, for AppImage integration'
    required: false
    default: ''
  app-ico:
    description: 'Path to .ico (Windows icon)'
    required: true
    default: ''
  app-icns:
    description: 'Path to .icns (macOS icon)'
    required: true
    default: ''
  app-png:
    description: 'Path to .png (Linux icon)'
    required: true
    default: ''
  qml-files:
    description: 'Space-separated list of QML files or directories to include'
    required: true
  qrc-file:
    description: 'Path to a .qrc file to bundle resources'
    required: false
  score-file:
    description: 'Score file to autoplay (optional)'
    required: false
    default: ''
  release-tag:
    description: 'ossia score release tag to use (default: continuous)'
    required: false
    default: 'continuous'
  score-build-id:
    description: 'An artifact id that contains a built version of score, e.g. built with the custom-score-build action'
    required: false
  output-path:
    description: 'Output directory for generated packages'
    required: false
    default: 'packages'
  platforms:
    description: 'Space-separated list of platforms to build for (linux-x86_64 linux-aarch64 macos-intel macos-arm windows). If empty, builds for current platform.'
    required: false
    default: ''
  score-repo:
    description: 'Repository containing ossia score and tools/create-app.sh script'
    required: false
    default: 'https://github.com/ossia/score.git'
  score-ref:
    description: 'Branch of score repository to use'
    required: false
    default: 'master'
  macos-certificate-base64:
    description: 'Base64-encoded P12 certificate for macOS code signing (optional)'
    required: false
    default: ''
  macos-certificate-password:
    description: 'Password for macOS P12 certificate (optional)'
    required: false
    default: ''
  macos-notarize-team-id:
    description: 'Apple Developer Team ID for notarization (optional)'
    required: false
    default: ''
  macos-notarize-apple-id:
    description: 'Apple ID for notarization (optional)'
    required: false
    default: ''
  macos-notarize-password:
    description: 'App-specific password for notarization (optional)'
    required: false
    default: ''

outputs:
  packages-path:
    description: 'Path to the generated packages directory'
    value: ${{ steps.set-output.outputs.packages-path }}

runs:
  using: 'composite'
  steps:
    - name: Checkout ossia score repository
      uses: actions/checkout@v4
      with:
        repository: ossia/score
        path: score-tools
        ref: ${{ inputs.score-ref }}
        sparse-checkout: |
          tools/create-app.sh
          tools/create-app-linux.sh
          tools/create-app-macos.sh
          tools/create-app-windows.sh
          tools/launcher/launcher.cpp
        sparse-checkout-cone-mode: false

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      if: inputs.qrc-file != ''
      with:
        add-tools-to-path: true
        version: '6.10.1'

    - name: Make scripts executable
      shell: bash
      run: |
        chmod +x score-tools/tools/create-app*.sh

    - name: Validate inputs
      shell: bash
      run: |
        # Validate QML files exist
        for item in ${{ inputs.qml-files }}; do
          if [[ ! -e "$item" ]]; then
            echo "Error: QML file or directory does not exist: $item"
            exit 1
          fi
        done

        # Validate score file if provided
        if [[ -n "${{ inputs.score-file }}" ]] && [[ ! -f "${{ inputs.score-file }}" ]]; then
          echo "Error: Score file does not exist: ${{ inputs.score-file }}"
          exit 1
        fi

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          p7zip-full \
          curl \
          wget \
          file \
          desktop-file-utils \
          zsync

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # Install required tools for macOS packaging
        brew install p7zip || true
        brew install create-dmg || true
        # Ensure developer tools are available
        xcode-select --install 2>/dev/null || true

    - name: Import code signing certificate (macOS)
      if: runner.os == 'macOS' && inputs.macos-certificate-base64 != '' && inputs.score-build-id == ''
      uses: jcelerier/import-codesign-certs@master
      with:
        p12-file-base64: ${{ inputs.macos-certificate-base64 }}
        p12-password: ${{ inputs.macos-certificate-password }}

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        # Install required tools for Windows packaging
        choco install 7zip -y

    - name: Set up paths
      shell: bash
      run: |
        # Store the repository root as absolute path
        REPO_ROOT=$(pwd)
        echo "REPO_ROOT=$REPO_ROOT" >> $GITHUB_ENV

        # Store the score tools directory as absolute path
        SCORE_TOOLS_DIR="$REPO_ROOT/score-tools/tools"
        echo "SCORE_TOOLS_DIR=$SCORE_TOOLS_DIR" >> $GITHUB_ENV

        # Create and store absolute output path
        mkdir -p "${{ inputs.output-path }}"
        OUTPUT_PATH=$(cd "${{ inputs.output-path }}" && pwd)
        echo "OUTPUT_PATH=$OUTPUT_PATH" >> $GITHUB_ENV

    - name: Download built packages
      uses: actions/download-artifact@v7
      if: inputs.score-build-id != ''
      with:
        artifact-ids: ${{ inputs.score-build-id }}
        path: score-build

    - name: Build package arguments
      shell: bash
      run: |
        # Build QML arguments with absolute paths
        QML_ARGS=""
        for item in ${{ inputs.qml-files }}; do
          # Convert to absolute path
          if [[ "$item" = /* ]]; then
            ABS_ITEM="$item"
          else
            ABS_ITEM="$REPO_ROOT/$item"
          fi
          QML_ARGS="$QML_ARGS --qml \"$ABS_ITEM\""
        done
        echo "QML_ARGS=$QML_ARGS" >> $GITHUB_ENV

        # Build score argument with absolute path
        if [[ -n "${{ inputs.score-file }}" ]]; then
          SCORE_FILE="${{ inputs.score-file }}"
          if [[ "$SCORE_FILE" = /* ]]; then
            ABS_SCORE="$SCORE_FILE"
          else
            ABS_SCORE="$REPO_ROOT/$SCORE_FILE"
          fi
          echo "SCORE_ARG=--score \"$ABS_SCORE\"" >> $GITHUB_ENV
        else
          echo "SCORE_ARG=" >> $GITHUB_ENV
        fi

        # Build platform arguments
        if [[ -n "${{ inputs.platforms }}" ]]; then
          PLATFORM_ARGS=""
          for platform in ${{ inputs.platforms }}; do
            PLATFORM_ARGS="$PLATFORM_ARGS --platform $platform"
          done
          echo "PLATFORM_ARGS=$PLATFORM_ARGS" >> $GITHUB_ENV
        else
          echo "PLATFORM_ARGS=" >> $GITHUB_ENV
        fi

    - name: Create custom app packages
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          export SCORE_LOCAL_INSTALLER=score-build/*.AppImage

          if [[ -n "${{ inputs.qrc-file }}" ]]; then
            RCC_PATH=$(find .. -name rcc -type f)
            export PATH="$PATH:$PWD/$(dirname $RCC_PATH)"
          fi
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          export SCORE_LOCAL_INSTALLER=score-build/*.exe

          if [[ -n "${{ inputs.qrc-file }}" ]]; then
            RCC_PATH=$(find .. -name rcc.exe -type f)
            export PATH="$PATH:$PWD/$(dirname $RCC_PATH)"
          fi
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          export SCORE_LOCAL_INSTALLER=score-build/*.dmg

          if [[ -n "${{ inputs.qrc-file }}" ]]; then
            RCC_PATH=$(find .. -name rcc -type f)
            export PATH="$PATH:$PWD/$(dirname $RCC_PATH)"
          fi
        fi

        # Run from the repository root, not from the tools directory
        cd "$REPO_ROOT"

        # Set up code signing environment variables for macOS
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          # Export code signing identity if certificate was imported
          if [[ -n "${{ inputs.macos-notarize-apple-id }}" ]]; then
            # FIXME
            echo "Setting up code signing with identity: ossia.io"
            export MAC_CODESIGN_IDENTITY="ossia.io"
          else
            echo "No certificate provided, skipping code signing"
          fi

          # Export notarization credentials if available
          if [[ -n "${{ inputs.macos-notarize-team-id }}" ]]; then
            echo "Setting up notarization credentials"
            export MAC_NOTARIZE_TEAM_ID="${{ inputs.macos-notarize-team-id }}"
            export MAC_NOTARIZE_APPLE_ID="${{ inputs.macos-notarize-apple-id }}"
            export MAC_NOTARIZE_PASSWORD="${{ inputs.macos-notarize-password }}"
          else
            echo "No notarization credentials provided"
          fi

          # Debug: show what's set (without revealing secrets)
          echo "MAC_CODESIGN_IDENTITY: ${MAC_CODESIGN_IDENTITY:-not set}"
          echo "MAC_NOTARIZE_TEAM_ID: ${MAC_NOTARIZE_TEAM_ID:-not set}"
        fi

        # Build the command with absolute path to script
        CMD="$SCORE_TOOLS_DIR/create-app.sh"
        CMD="$CMD ${{ env.QML_ARGS }}"
        CMD="$CMD ${{ env.SCORE_ARG }}"
        CMD="$CMD --output \"${{ env.OUTPUT_PATH }}\""

        if [[ -n "${{ inputs.score-build-id }}" ]]; then
          CMD="$CMD --local-installer $SCORE_LOCAL_INSTALLER"
        elif [[ -n "${{ inputs.release-tag }}" ]]; then
          CMD="$CMD --release \"${{ inputs.release-tag }}\""
        else
          echo "One of release-tag or score-build-id has to be set"
          exit 1
        fi

        CMD="$CMD --app-name \"${{ inputs.app-name }}\""
        CMD="$CMD --app-organization \"${{ inputs.app-organization }}\""
        CMD="$CMD --app-domain \"${{ inputs.app-domain }}\""
        CMD="$CMD --app-identifier \"${{ inputs.app-identifier }}\""
        CMD="$CMD --app-description \"${{ inputs.app-description }}\""
        CMD="$CMD --app-copyright \"${{ inputs.app-copyright }}\""

        if [[ -n "${{ inputs.qrc-file }}" ]]; then
          CMD="$CMD --app-qrc $PWD/${{ inputs.qrc-file }}"
        fi

        if [[ -n "${{ inputs.app-environment }}" ]]; then
          CMD="$CMD --app-environment $PWD/${{ inputs.app-environment }}"
        fi

        CMD="$CMD --app-version \"${{ inputs.app-version }}\""
        CMD="$CMD --app-appdata-xml $PWD/\"${{ inputs.app-appdata-xml }}\""
        CMD="$CMD --app-ico $PWD/\"${{ inputs.app-ico }}\""
        CMD="$CMD --app-icns $PWD/\"${{ inputs.app-icns }}\""
        CMD="$CMD --app-png $PWD/\"${{ inputs.app-png }}\""
        CMD="$CMD ${{ env.PLATFORM_ARGS }}"

        echo "Executing from: $(pwd)"
        echo "Command: $CMD"

        eval "$CMD"

    - name: Set output path
      id: set-output
      shell: bash
      run: |
        echo "packages-path=${{ env.OUTPUT_PATH }}" >> $GITHUB_OUTPUT

    - name: Display created packages
      shell: bash
      run: |
        echo "Created packages:"
        ls -lah "${{ env.OUTPUT_PATH }}"
