name: JIT

on:
  workflow_call:

jobs:
  jit:
    name: "JIT ${{ matrix.config.name }} ${{ matrix.version }}"
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        version: [ "latest", "continuous" ]
        config:
          - { name: "Windows", os: windows-latest }
          - { name: "Ubuntu", os: ubuntu-latest }
          - { name: "macOS", os: macos-15 }

    steps:
      - name: Support longpaths
        run: git config --global core.longpaths true

      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          path: addon

      - name: Download Score SDK
        uses: ossia/actions/download-score-sdk@master
        with:
          version: "${{ matrix.version }}"
          extract-path: "./sdk"

      - name: JIT compile test
        uses: ossia/actions/jit-compile@master
        with:
          score-version: ${{ matrix.version }}
          sdk-path: "./sdk/usr"
          addon-path: "./addon"
